In [12]:
import pandas as pd
import string
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [3]:
blurbs = pd.read_csv('../raw_data/books_with_blurbs.csv')

In [4]:
blurbs.head()

,ISBN,Title,Author,Year,Publisher,Blurb
0,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,"Here, for the first time in paperback, is an o..."
1,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,"The fascinating, true story of the world's dea..."
2,0399135782,The Kitchen God's Wife,Amy Tan,1991,Putnam Pub Group,Winnie and Helen have kept each others worst s...
3,0425176428,What If?: The World's Foremost Military Histor...,Robert Cowley,2000,Berkley Publishing Group,Historians and inquisitive laymen alike love t...
4,1881320189,Goodbye to the Buttermilk Sky,Julia Oliver,1994,River City Pub,This highly praised first novel by fiction wri...

In [16]:
blurbs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57510 entries, 0 to 57509
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   ISBN       57510 non-null  object
 1   Title      57510 non-null  object
 2   Author     57510 non-null  object
 3   Year       57510 non-null  int64
 4   Publisher  57510 non-null  object
 5   Blurb      57510 non-null  object
dtypes: int64(1), object(5)
memory usage: 2.6+ MB

In [5]:
songs = pd.read_csv('../raw_data/spotify_millsongdata.csv')
songs.head()

,artist,song,link,text
0,ABBA,Ahe's My Kind Of Girl,/a/abba/ahes+my+kind+of+girl_20598417.html,"Look at her face, it's a wonderful face \r\nA..."
1,ABBA,"Andante, Andante",/a/abba/andante+andante_20002708.html,"Take it easy with me, please \r\nTouch me gen..."
2,ABBA,As Good As New,/a/abba/as+good+as+new_20003033.html,I'll never know why I had to go \r\nWhy I had...
3,ABBA,Bang,/a/abba/bang_20598415.html,Making somebody happy is a question of give an...
4,ABBA,Bang-A-Boomerang,/a/abba/bang+a+boomerang_20002668.html,Making somebody happy is a question of give an...

In [13]:
def cleaning(sentence):
    
    # Basic cleaning
    sentence = sentence.strip() ## remove whitespaces
    sentence = sentence.lower() ## lowercase 
    sentence = ''.join(char for char in sentence if not char.isdigit()) ## remove numbers
    
    # Advanced cleaning
    for punctuation in string.punctuation:
        sentence = sentence.replace(punctuation, '') ## remove punctuation
    
    tokenized_sentence = word_tokenize(sentence) ## tokenize 
    stop_words = set(stopwords.words('english')) ## define stopwords
    
    tokenized_sentence_cleaned = [ ## remove stopwords
        w for w in tokenized_sentence if not w in stop_words
    ]
    
    cleaned_sentence = ' '.join(word for word in tokenized_sentence_cleaned)
    
    return cleaned_sentence

In [14]:
cleaning(songs["text"][0])

'look face wonderful face means something special look way smiles sees lucky one fellow shes kind girl makes feel fine could ever believe could mine shes kind girl without im blue ever leaves could could go walk park holds squeezes hand well go walking hours talking things plan shes kind girl makes feel fine could ever believe could mine shes kind girl without im blue ever leaves could could'

In [15]:
blurbs_cleaned = blurbs.copy()
blurbs_cleaned["Blurb_cleaned"] = blurbs_cleaned["Blurb"].apply(cleaning)

In [17]:
blurbs_cleaned.head()

,ISBN,Title,Author,Year,Publisher,Blurb,Blurb_cleaned
0,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,"Here, for the first time in paperback, is an o...",first time paperback outstanding military hist...
1,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,"The fascinating, true story of the world's dea...",fascinating true story worlds deadliest diseas...
2,0399135782,The Kitchen God's Wife,Amy Tan,1991,Putnam Pub Group,Winnie and Helen have kept each others worst s...,winnie helen kept others worst secrets fifty y...
3,0425176428,What If?: The World's Foremost Military Histor...,Robert Cowley,2000,Berkley Publishing Group,Historians and inquisitive laymen alike love t...,historians inquisitive laymen alike love ponde...
4,1881320189,Goodbye to the Buttermilk Sky,Julia Oliver,1994,River City Pub,This highly praised first novel by fiction wri...,highly praised first novel fiction writer juli...

In [19]:
songs_cleaned = songs.copy()
songs_cleaned["text_cleaned"] = songs_cleaned["text"].apply(cleaning)

In [20]:
songs_cleaned.head()

,artist,song,link,text,text_cleaned
0,ABBA,Ahe's My Kind Of Girl,/a/abba/ahes+my+kind+of+girl_20598417.html,"Look at her face, it's a wonderful face \r\nA...",look face wonderful face means something speci...
1,ABBA,"Andante, Andante",/a/abba/andante+andante_20002708.html,"Take it easy with me, please \r\nTouch me gen...",take easy please touch gently like summer even...
2,ABBA,As Good As New,/a/abba/as+good+as+new_20003033.html,I'll never know why I had to go \r\nWhy I had...,ill never know go put lousy rotten show boy to...
3,ABBA,Bang,/a/abba/bang_20598415.html,Making somebody happy is a question of give an...,making somebody happy question give take learn...
4,ABBA,Bang-A-Boomerang,/a/abba/bang+a+boomerang_20002668.html,Making somebody happy is a question of give an...,making somebody happy question give take learn...

# Modelo Vader

In [26]:
import nltk
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     /home/silvhera/nltk_data...

True

In [27]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

# Importar el tokenizador Punkt (si no lo has hecho antes)
from nltk import download
download('punkt')

[nltk_data] Downloading package punkt to /home/silvhera/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [28]:
sia = SentimentIntensityAnalyzer()

In [32]:
songs_cleaned.head()

,artist,song,link,text,text_cleaned
0,ABBA,Ahe's My Kind Of Girl,/a/abba/ahes+my+kind+of+girl_20598417.html,"Look at her face, it's a wonderful face \r\nA...",look face wonderful face means something speci...
1,ABBA,"Andante, Andante",/a/abba/andante+andante_20002708.html,"Take it easy with me, please \r\nTouch me gen...",take easy please touch gently like summer even...
2,ABBA,As Good As New,/a/abba/as+good+as+new_20003033.html,I'll never know why I had to go \r\nWhy I had...,ill never know go put lousy rotten show boy to...
3,ABBA,Bang,/a/abba/bang_20598415.html,Making somebody happy is a question of give an...,making somebody happy question give take learn...
4,ABBA,Bang-A-Boomerang,/a/abba/bang+a+boomerang_20002668.html,Making somebody happy is a question of give an...,making somebody happy question give take learn...

In [29]:
sia.polarity_scores(songs_cleaned["text_cleaned"][0])

{'neg': 0.0, 'neu': 0.621, 'pos': 0.379, 'compound': 0.9859}

In [33]:
sia.polarity_scores(songs_cleaned["text_cleaned"][0])["compound"]

0.9859

In [37]:
def obtain_compound(text):
    sia = SentimentIntensityAnalyzer()
    scores = sia.polarity_scores(text)
    return scores['compound']

In [38]:
songs_sentiment = songs_cleaned.copy()
songs_sentiment["sentiment"] = songs_cleaned["text_cleaned"].apply(obtain_compound)

In [40]:
blurbs_sentiment = blurbs_cleaned.copy()
blurbs_sentiment["sentiment"] = blurbs_cleaned["Blurb_cleaned"].apply(obtain_compound)

In [55]:
def playlist_by_book(title):
    book_sentiment = blurbs_sentiment.loc[blurbs_sentiment["Title"] == title, "sentiment"].values[0]
    songs_sentiment['abs_dif'] = abs(songs_sentiment['sentiment'] - book_sentiment)
    playlist = songs_sentiment.nsmallest(20, 'abs_dif')
    return playlist

In [56]:
blurbs_sentiment.head()

,ISBN,Title,Author,Year,Publisher,Blurb,Blurb_cleaned,sentiment
0,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,"Here, for the first time in paperback, is an o...",first time paperback outstanding military hist...,0.6124
1,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,"The fascinating, true story of the world's dea...",fascinating true story worlds deadliest diseas...,-0.9552
2,0399135782,The Kitchen God's Wife,Amy Tan,1991,Putnam Pub Group,Winnie and Helen have kept each others worst s...,winnie helen kept others worst secrets fifty y...,-0.8957
3,0425176428,What If?: The World's Foremost Military Histor...,Robert Cowley,2000,Berkley Publishing Group,Historians and inquisitive laymen alike love t...,historians inquisitive laymen alike love ponde...,0.8625
4,1881320189,Goodbye to the Buttermilk Sky,Julia Oliver,1994,River City Pub,This highly praised first novel by fiction wri...,highly praised first novel fiction writer juli...,0.9720

In [58]:
playlist_by_book("Pride and Prejudice")

,artist,song,link,text,text_cleaned,sentiment,abs_dif
2252,Cat Stevens,Drywood,/c/cat+stevens/drywood_20028174.html,"You've got to learn, to brighten up your ways ...",youve got learn brighten ways kick dull padded...,0.9935,0.0
3882,Dean Martin,Bella Bella Bambina,/d/dean+martin/bella+bella+bambina_20155835.html,Bella bella bambina \r\nBella bella bambina ...,bella bella bambina bella bella bambina mandol...,0.9935,0.0
4406,Donna Summer,Lucky,/d/donna+summer/lucky_20042212.html,Scared and lonely \r\nGoing out for the night...,scared lonely going night shakin wishing id ne...,0.9935,0.0
5322,Eric Clapton,Behind The Mask,/e/eric+clapton/behind+the+mask_20051125.html,"[Chorus:] \r\nAll along, had to talk about it...",chorus along talk like twoedged sword touched ...,0.9935,0.0
5478,Etta James,We're In Love,/e/etta+james/were+in+love_20822826.html,"Love, we're in love \r\n \r\nI know \r\n(I ...",love love know know know know know love know k...,0.9935,0.0
6162,Fleetwood Mac,Like It This Way,/f/fleetwood+mac/like+it+this+way_20054205.html,Better love me baby \r\nLove me all the time ...,better love baby love time better love baby le...,0.9935,0.0
7074,Gordon Lightfoot,Bend In The Water,/g/gordon+lightfoot/bend+in+the+water_20061523...,"Come on Pearl, come on Kitty, \r\nIf you feel...",come pearl come kitty feel inclined around ben...,0.9935,0.0
8476,Indigo Girls,Perfect World,/i/indigo+girls/perfect+world_20295896.html,"We get to be, a ripple in the water \r\nWe ge...",get ripple water get rock thats thrown get boy...,0.9935,0.0
9854,Joy Division,A Means To An End,/j/joy+division/a+means+to+an+end_20075871.html,"A legacy so far removed, \r\nOne day will be ...",legacy far removed one day improved eternal ri...,0.9935,0.0
10114,Kate Bush,Kite,/k/kate+bush/kite_20077172.html,(Come up and be a kite) \r\n \r\nBeelzebub i...,come kite beelzebub aching bellyo feet heavy i...,0.9935,0.0
10493,Kenny Rogers,Silent Night,/k/kenny+rogers/silent+night_20241769.html,Silent Night \r\nHoly Night \r\nAll is calm ...,silent night holy night calm bright round yon ...,0.9935,0.0
10947,Kris Kristofferson,Forever In Your Love,/k/kris+kristofferson/forever+in+your+love_200...,Lovers make believe in dreams \r\nDreamers ma...,lovers make believe dreams dreamers make belie...,0.9935,0.0
11645,Linda Ronstadt,Life Is Like A Mountain Railway,/l/linda+ronstadt/life+is+like+a+mountain+rail...,Life is like a mountain railway \r\nWith an e...,life like mountain railway engineer thats brav...,0.9935,0.0
11885,Lorde,The Love Club,/l/lorde/the+love+club_21064021.html,I'm in a clique but I want out \r\nIt's not t...,im clique want punched old days enough card ga...,0.9935,0.0
12239,Luther Vandross,Sugar And Spice (I Found Me A Girl),/l/luther+vandross/sugar+and+spice+i+found+me+...,Hey \r\nHey \r\nHey \r\n \r\nSugar and spi...,hey hey hey sugar spice righter right never fe...,0.9935,0.0
12316,Manowar,An American Trilogy,/m/manowar/an+american+trilogy_20279255.html,Oh I wish I was in the land of cotton \r\n \...,oh wish land cotton old times forgotten look a...,0.9935,0.0
14846,Old 97's,Weightless,/o/old+97s/weightless_10197055.html,I reckon Heaven is a place \r\nWhere time is ...,reckon heaven place time nonexistent yeah thin...,0.9935,0.0
14932,Omd,Telegraph,/o/omd/telegraph_20103414.html,I've got a telegraph in my hand \r\nWords on ...,ive got telegraph hand words paper written san...,0.9935,0.0
16416,Prince,Girl,/p/prince/girl_20111260.html,"Girl \r\nYou excite me so \r\nOoh wee baby, ...",girl excite ooh wee baby bodys like girl got t...,0.9935,0.0
17624,Rihanna,A Girl Like Me,/r/rihanna/a+girl+like+me_20409523.html,Some girls play the game \r\nThey all walk an...,girls play game walk talk dress nothin new say...,0.9935,0.0